#include <stdio.h>

int TR_help(void) {
  printf("Usage:\n"
         "  traceroute [ -f first_ttl ] [ -m max_ttl ] [ -p port ] "
         "[ -w MAX,HERE,NEAR ] [ -q nqueries ] host [ packetlen ]\n"
         "Options:\n"
         "  -p port  --port=port        Set the destination port to use.\n"
         "                              (incremented by each probe, default is "
         "33434)\n"
         "  -f first_ttl  --first=first_ttl\n"
         "                              Start from the first_ttl hop (instead "
         "from 1)\n"
         "  -m max_ttl  --max-hops=max_ttl\n"
         "                              Set the max number of hops (max TTL to "
         "be\n"
         "                              reached). Default is 30\n"
         "  -q nqueries  --queries=nqueries\n"
         "                              Set the number of probes per each hop. "
         "Default is\n"
         "                              3\n"
         "  -w MAX,HERE,NEAR  --wait=MAX,HERE,NEAR\n"
         "                              Wait for a probe no more than HERE "
         "(default 3)\n"
         "                              times longer than a response from the "
         "same hop,\n"
         "                              or no more than NEAR (default 10) "
         "times than some\n"
         "                              next hop, or MAX (default 5.0) seconds "
         "(float\n"
         "                              point values allowed too)\n"
         "  --help                      Read this help and exit\n"
         "\n"
         "Arguments:\n"
         "+     host          The host to traceroute to\n"
         "      packetlen     The full packet length (default is the length of "
         "an IP\n"
         "                    header plus 40). Can be ignored or increased to "
         "a minimal\n"
         "                    allowed value\n");
  return 0;
}
